#!/usr/bin/env bash
#
# setup.sh - Install sayd (speech-to-text daemon + GNOME Shell extension)
#
# Run from the directory containing this script.

set -euo pipefail

DAEMON_DIR="$HOME/.local/share/sayd"
EXT_DIR="$HOME/.local/share/gnome-shell/extensions/sayd@local"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Dependency check + optional auto-install
# ---------------------------------------------------------------------------

echo "==> Checking system dependencies..."
MISSING=()
command -v ydotool >/dev/null 2>&1 || MISSING+=("ydotool")
command -v python3  >/dev/null 2>&1 || MISSING+=("python3")

if [ ${#MISSING[@]} -ne 0 ]; then
    echo ""
    echo "Missing system packages: ${MISSING[*]}"
    read -rp "Install them now with sudo dnf? [Y/n] " ans
    ans="${ans:-Y}"
    if [[ "$ans" =~ ^[Yy]$ ]]; then
        sudo dnf install -y "${MISSING[@]}"
    else
        echo "Skipping install. sayd may not work without these packages."
    fi
fi

# ---------------------------------------------------------------------------
# Daemon
# ---------------------------------------------------------------------------

echo ""
echo "==> Creating daemon directory: $DAEMON_DIR"
mkdir -p "$DAEMON_DIR"

echo "==> Copying sayd-daemon.py"
cp "$SCRIPT_DIR/sayd-daemon.py" "$DAEMON_DIR/sayd-daemon.py"
chmod +x "$DAEMON_DIR/sayd-daemon.py"

echo "==> Setting up Python virtual environment"
python3 -m venv "$DAEMON_DIR/venv"
"$DAEMON_DIR/venv/bin/pip" install --upgrade pip -q
"$DAEMON_DIR/venv/bin/pip" install faster-whisper sounddevice numpy -q

# ---------------------------------------------------------------------------
# launch-daemon.sh  (written here so the python version is always correct)
# ---------------------------------------------------------------------------

PYVER=$("$DAEMON_DIR/venv/bin/python3" -c \
    "import sys; print(f'python{sys.version_info.major}.{sys.version_info.minor}')")
PYLIB="$DAEMON_DIR/venv/lib/$PYVER/site-packages"

echo "==> Writing launch-daemon.sh (Python: $PYVER)"
cat > "$DAEMON_DIR/launch-daemon.sh" << LAUNCH
#!/usr/bin/env bash
# Auto-generated by setup.sh — re-run setup.sh to regenerate.
set -euo pipefail

DAEMON_DIR="\$HOME/.local/share/sayd"
VENV="\$DAEMON_DIR/venv"
PYLIB="$PYLIB"

# Add nvidia pip-package lib dirs to LD_LIBRARY_PATH so ctranslate2
# can find cuBLAS/cuDNN without a system-level CUDA install.
EXTRA_LD_PATHS=""
for pkg in cublas cudnn cuda_nvrtc cuda_runtime cuda_cupti; do
    libdir="\$PYLIB/nvidia/\$pkg/lib"
    [ -d "\$libdir" ] && EXTRA_LD_PATHS="\$EXTRA_LD_PATHS:\$libdir"
done
export LD_LIBRARY_PATH="\${EXTRA_LD_PATHS#:}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"

# Ensure ydotoold is running.
SOCKET="\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}/.ydotool_socket"
if ! pgrep -u "\$(id -u)" -x ydotoold >/dev/null 2>&1; then
    rm -f "\$SOCKET" 2>/dev/null || true
    nohup ydotoold >/dev/null 2>&1 &
    disown
    for _ in \$(seq 1 20); do [ -S "\$SOCKET" ] && break; sleep 0.1; done
fi

exec "\$VENV/bin/python3" "\$DAEMON_DIR/sayd-daemon.py" "\$@"
LAUNCH
chmod +x "$DAEMON_DIR/launch-daemon.sh"

# ---------------------------------------------------------------------------
# GNOME Shell extension
# ---------------------------------------------------------------------------

echo "==> Installing GNOME Shell extension to $EXT_DIR"
mkdir -p "$EXT_DIR"
cp -r "$SCRIPT_DIR/sayd@local/"* "$EXT_DIR/"

echo "==> Compiling GSettings schema"
glib-compile-schemas "$EXT_DIR/schemas"

echo "==> Enabling extension"
if command -v gnome-extensions >/dev/null 2>&1; then
    gnome-extensions enable sayd@local 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

cat <<'EOF'

==============================================================
sayd installed successfully.

Next steps:
  1. Log out and back in so GNOME Shell loads the extension.
     (Wayland doesn't support shell restarts without a re-login.)

  2. Press Super+H — the daemon starts in the background.
     First launch downloads the Whisper model (~250 MB) and may
     take 20–30 seconds.

  3. The top-bar mic icon shows:
       dim grey   — daemon not running
       yellow     — model loading
       solid grey — idle, ready to record
       red pulse  — recording

  4. Press Super+H again to start/stop recording. Transcribed
     text is typed into whatever window has focus.

  5. Right-click the icon → "Quit & Free GPU" to shut the
     daemon down and free GPU/CPU memory.

Files:
  Daemon:  ~/.local/share/sayd/
  Log:     ~/.local/share/sayd/daemon.log
  Config:  ~/.config/sayd/config.json
  Socket:  ~/.local/share/sayd/control.sock

GPU note:
  The daemon tries CUDA first and falls back to CPU automatically.
  For GPU transcription, install the CUDA pip packages:
    ~/.local/share/sayd/venv/bin/pip install \
        nvidia-cublas-cu12 nvidia-cudnn-cu12
==============================================================
EOF
